import streamlit as st
from dotenv import load_dotenv
import os
from interview_practice_app.LLM_manager_class import LLM_Manager
from interview_practice_app.Interview_manager_class import Interview_Manager

ACCEPTED_FILE_TYPES = ["txt", "pdf", "doc", "docx"]
DIFFICULTY_LEVELS = ["easy", "medium", "hard"]
LLM_output = ["Which Python data type is mutable and stores key-value pairs?", "Which condition checks equal values in Python?"]


def main():
    load_dotenv()
    llm_manager = LLM_Manager()
    interview_manager = Interview_Manager()
    st.title("Welcome to Interview Practice App!")
    st.header("Ace your interview practice in 5 easy steps.") 
    st.subheader("Step 1: Upload a job description or copy-paste it into the text box below.")
    uploaded_file = st.file_uploader("Choose a file", accept_multiple_files=False, type=ACCEPTED_FILE_TYPES)
    if uploaded_file is not None:
        bytes_data = uploaded_file.getvalue()
        st.write(bytes_data)
    st.text_area("Job description", key="job_description")
    st.subheader("Step 2: Define the number and difficulty of questions to be generated for your practice interview.")
    st.number_input("Number of questions", min_value=1, max_value=10, value=5, key="num_questions")
    st.selectbox("Difficulty level", DIFFICULTY_LEVELS, key="difficulty")
    st.subheader("Step 3: Generate questions using OpenAI API.")
    st.button("Generate", on_click=llm_manager.generate_questions, args=(st.session_state.job_description, st.session_state.num_questions, st.session_state.difficulty))
    st.subheader("Step 4: Review the questions generated by OpenAI.")
    st.button("Confirm selection", on_click=interview_manager.review_questions(LLM_output))
    #st.subheader("Step 5: Practice answering the questions and get feedback from OpenAI. Your answers and feedback will be automatically saved.")
    #st.button("Evaluate", on_click=llm_manager.evaluate_answers, args=(st.session_state.job_description, st.session_state.answer))
    #st.button("Save", on_click=llm_manager.save_answers, args=(st.session_state.job_description, st.session_state.answer))

if __name__ == "__main__":
    main()
