import streamlit as st

question_review_options = ["Accept the question as-is", "Modify the question and accept it with modifications", "Reject the question"]

class Interview_Manager:
    """
    Manages all interview-related interactions.

    The class has three main methods:
    - review_questions: Allows the user to review the questions generated by LLM and accept, modify, or reject them.
    - practice_interview: Allows the user to practice answering the questions and get feedback from LLM.
    - save_feedback: Allows the user to save the feedback from LLM once a practice session is completed.

    """
    def __init__(self, list_of_questions: list = []) -> None:
        """Initializes a new Interview_Manager instance."""
        self._list_of_questions = list_of_questions

    def __str__(self) -> str:
        """Returns a string representation of the Interview_Manager."""
        return "Interview Manager for interview practice."

    def review_questions(self, LLM_output: list) -> list[Question]:
        """
        Parses the LLM output and allows the user to review, modify, or reject questions.

        Args:
            LLM_output (list): The raw output (list of strings) from the LLM.

        Returns:
            list[Question]: A list of accepted and/or modified Question objects.
        """
        generated_questions = LLM_output
        if len(generated_questions) == 1:
            st.write("In total, 1 question has been generated - please review:")
        else:
            st.write(f"In total, {len(generated_questions)} questions have been generated - please review:")
        for i, q in enumerate(generated_questions, start=1):
            st.write(
                f"Question {i} of {len(generated_questions)}:\n\n {q}"
            )
            while True:
                question_review_option = st.selectbox(
                    "Please choose one of the following options:", 
                    question_review_options,
                    key=f"question_review_option_{i}"
                )
                if question_review_option == "Accept the question as-is":
                    self._list_of_questions.append(q)
                    break
                elif question_review_option == "Modify the question and accept it with modifications":
                    while True:
                        original_text = q
                        modified_text = st.text_input(
                            "Enter modified question text: ",
                            value=original_text
                        )
                        if not modified_text or modified_text.strip() == "":
                            st.write("Modified question cannot be blank. Please try again.")
                        elif modified_text == original_text:
                            break
                        else:
                            q = modified_text
                            break
                else:
                    st.write("The question has been rejected.")
                    break
        return self._list_of_questions